### ISSUE TITLE
建议把 Contributions 加入组织

### ISSUE THREAD

**Issue by dbarobin** [wiiiky/scope#12]
如题，既然是个组织，建议把 Contributions 加进去。可以通过 [此处](http://git.io/vfIQi) 看到此项目的 Contributions。另外，建议补充 `scope-doc` 的相关信息，比如头像、描述等。

**Comment by dbarobin** [comment]
英文写错了，应该是 **Contributors**，抱歉。

**Comment by wiiiky** [comment]
因为都只是编辑完一次就不关注了，所以没有必要加吧。不过可以把你加进来。

**Comment by dbarobin** [comment]
其实一个文档需要长期维护的。

**Comment by wiiiky** [comment]
最近我在搜集其他职位的信息
