### ISSUE TITLE
相见恨晚

### ISSUE THREAD

**Issue by ideazhao** [wiiiky/scope#15]
偶然在鬼哥博客文章里看到你们的项目，我也做了一个项目http://f2er.club/
其实初衷跟你的项目差不多，是为了让所有从事前端的人不再那么无方向，不再大海捞针。有可能的话，可以合作，另外想问你们也是web形式的吗？还没上线？

**Comment by wiiiky** [comment]
很高兴你能联系我，不过你应该也已经看到了，scope已经很久没有维护了。

因为之前主要就我一个人在做，很容易越做越没劲。

事实上是这样的，我其实是想把职位整理出来，工作内容，所需要技能什么的；如果做得好，我甚至想，可以做一个APP，功能有两个，

一个就是查看这些职位信息；

另一个是让用户选择职位方向，然后输入自己会的技能，可以给他匹配出他当前技能适合哪些职位，以及欠缺什么技能之类的。

如果你也想在这个项目上继续做的话，我们可以重新讨论一下。

Date: Tue, 8 Sep 2015 08:33:57 -0700

**Comment by wiiiky** [comment]
现在的内容，因为是不同人编辑的，所以格式，风格什么的都不够统一。而且也不够丰富我觉得。

**Comment by wiiiky** [comment]
也许应该先缩小范围，把其中几个职位内容做好做精了。

**Comment by ideazhao** [comment]
@wiiiky 一个人做没什么大不了，我也是一个人，看你有多想做了，而且这个东西是需要时间积累和心思的，希望你能坚持下去，后续我也会在我的站上完善相关的内容，但不会做得太细致，你如果做网站的话，我是会把你的加进来

**Comment by ideazhao** [comment]
@wiiiky 在时间允许的情况下，我乐意和你一起做好它

**Comment by wiiiky** [comment]
先关闭，过段时间我会回来的
