### ISSUE TITLE
文档内容

### ISSUE THREAD

**Issue by wiiiky** [wiiiky/scope#7]
如果认为需要增加哪部分内容，或者怎么样的，可以在这里提。反正目标就是让在校学生看了能对职业有很实际的认识。

**Comment by dbarobin** [comment]
重新排版，参考：http://git.io/ppzb

**Comment by wiiiky** [comment]
你是指src下面的文档还是根目录的readme。
如果是src下面的，我是想之后每个要整理编辑出一份的。
readme的话现在好像还是基本规范的

**Comment by dbarobin** [comment]
主要是 src 吧。

**Comment by wiiiky** [comment]
我重新设计了文档的内容。主要改变如下
-    职业现状改成了职业介绍，包含现状、发展等相关的内容；
-    把原来的工作内容和工作场景合并为了工作内容；
-    去掉了合作对象，这个在工作内容中有提到就好，不需要再单独拿出来了；
-    把信息源分成参考资料和信息源，参考资料只包含书，信息源只包含链接；
-    添加了知识点水平1-5的说明，希望能尽可能统一不同人的标准。

然后 Python 和 Android 我已经更新，其他的也会慢慢补上。

**Comment by wiiiky** [comment]
@dbarobin 你觉得新的内容组织怎么样，我觉得比之前的更清楚，也更加有意义。

**Comment by dbarobin** [comment]
Well done!

**Comment by wiiiky** [comment]
我现在发现，这种文档很多人都写不出来，也许他们能说出来。好尴尬。
